<a href="https://colab.research.google.com/github/nicholassolomon/dlwpt-code/blob/master/Chapter_3_mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 3 - Tensors

* https://learning.oreilly.com/library/view/deep-learning-with/9781617295263/Text/03.xhtml

```
01.14.24:
```
Colab Folder: DLWPT

## 0 Setup

In [ ]:
import torch

# get data from book repo
!git clone https://github.com/deep-learning-with-pytorch/dlwpt-code.git
!mv dlwpt-code/data .
!rm -rf dlwpt-code

# set device
device = "cuda" if torch.cuda.is_available() else "cpu"
device


Cloning into 'dlwpt-code'...
remote: Enumerating objects: 703, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 703 (delta 106), reused 87 (delta 87), pack-reused 554
Receiving objects: 100% (703/703), 175.17 MiB | 22.51 MiB/s, done.
Resolving deltas: 100% (318/318), done.
Updating files: 100% (228/228), done.


'cuda'

## 1 Tensors

Tensor API: http://pytorch.org/docs

* `einsum`: assign names to index values
* `refine_names`: change existing index names
* `storage()`
* `stride()`
* `storage_offset()`
* `clone()`
* `points()`
* `transpose()`
* `is_contingous()`
* `to(dtype=torch.short)`
* `save(), load()`
* `size()`




In [ ]:
a = torch.ones(3)
print(f"{'Tensor:':<15}{a}")
print(f"{'Python type:':<15}{type(a)}")
print(f"{'Datatype:':<15}{a.dtype}")
print(f"{'Shape:':<15}{a.shape}")
print(f"{'Length:':<15}{len(a)}")
print(f"{'Single element:':<15}{a[1]}")
print(f"{'Single value:':<15}{a[1].item()}")

Tensor:        tensor([1., 1., 1.])
Python type:   <class 'torch.Tensor'>
Datatype:      torch.float32
Shape:         torch.Size([3])
Length:        3
Single element:1.0
Single value:  1.0


In [ ]:
b = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])
print(f"{'Tensor:':<15}{b}")
print(f"{'Python type:':<15}{type(b)}")
print(f"{'Datatype:':<15}{b.dtype}")
print(f"{'Shape:':<15}{b.shape}")
print(f"{'Length:':<15}{len(b)}")
print(f"{'Single element:':<15}{b[0][1]}")
print(f"{'Single value:':<15}{b[0,1].item()}")
print(f"{'Range:':<15}{b[1:]}")



Tensor:        tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
Python type:   <class 'torch.Tensor'>
Datatype:      torch.float32
Shape:         torch.Size([3, 2])
Length:        3
Single element:1.0
Single value:  1.0
Range:         tensor([[5., 3.],
        [2., 1.]])


In [ ]:
a = [1.0, 2.0, 1.0]

In [ ]:
a[0]

1.0

In [ ]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [ ]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [ ]:
a[1]

tensor(1.)

In [ ]:
float(a[1])

1.0

In [ ]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [ ]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points.shape

torch.Size([3, 2])

In [ ]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points[0, 1]

tensor(1.)

In [ ]:
points[0]

tensor([4., 1.])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
points_storage = points.storage()
points_storage[0]

4.0

In [ ]:
points.storage()[1]

1.0

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [ ]:
second_point.size()

torch.Size([2])

In [ ]:
second_point.shape

torch.Size([2])

In [ ]:
points.stride()

(2, 1)

In [ ]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [ ]:
second_point.storage_offset()

2

In [ ]:
second_point.stride()

(1,)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
id(points.storage()) == id(points_t.storage())

True

In [ ]:
points.stride()

(2, 1)

In [ ]:
points_t.stride()

(1, 2)

In [ ]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [ ]:
transpose_t.shape

torch.Size([5, 4, 3])

In [ ]:
some_t.stride()

(20, 5, 1)

In [ ]:
transpose_t.stride()

(1, 5, 20)

In [ ]:
points.is_contiguous()

True

In [ ]:
points_t.is_contiguous()

False

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
points_t.stride()

(1, 2)

In [ ]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t_cont.stride()

(3, 1)

In [ ]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [ ]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [ ]:
short_points.dtype

torch.int16

In [ ]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [ ]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [ ]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [ ]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [ ]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [ ]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [ ]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
points = torch.from_numpy(points_np)

In [ ]:
torch.save(points, '../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [ ]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [ ]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [ ]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [ ]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [ ]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [ ]:
points_gpu = points.to(device='cuda')

In [ ]:
points_gpu = points.to(device='cuda:0')

In [ ]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [ ]:
points_gpu = points_gpu + 4

In [ ]:
points_cpu = points_gpu.to(device='cpu')

In [ ]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [ ]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
a = torch.ones(3, 2)

In [ ]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 2 Named Tensors

In [ ]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

In [ ]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [ ]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [ ]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [ ]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [ ]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [ ]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [ ]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [ ]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [ ]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [ ]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [ ]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

## 3 Excersises